
all:
	g++  zma.cpp common.cpp ini.c zkClient.cpp base64.cpp cJSON.c dispatcherTimer.cpp commands.cpp setDispose.cpp -I /home/service/include/zookeeper -I /home/service/include/curl -lrt -lpthread -lzookeeper_mt -o zma
